"use client";
import { MyContextProvider } from "./components/MyContext";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Eshkon",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <MyContextProvider>
        <body className={inter.className}>{children}</body>
      </MyContextProvider>
    </html>
  );
}
